# Generated by Django 4.1.7 on 2023-03-16 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do", "0002_alter_tag_options_alter_task_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
